changelog:
  categories:
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug fix
    - title: Refactors and Housekeeping
      labels:
        - refactor
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
